### PR TITLE
Re-Add Static File support

### PR DESCRIPTION
**Pull request by SentryMan**
Adds support for creating handlers that serve static resources. 

- Adds a `StaticContentConfig` class that will construct a handler to serve files
- Adds three static handlers. one for regular files, jars and another for more esoteric cases [like when using jlink](https://github.com/javalin/javalin/issues/2132)
- Re-add some Basic HttpResponse Exceptions (we don't need as many as we had before, but catching framework errors is pretty useful)

### CODE REVIEW

**Comment by SentryMan** [comment]
hmm, it would seem that it doesn't properly load when running a modular jar outside of jlink

**Comment by SentryMan** [comment]
@rbygrave please review when you find time

**Review by rbygrave — APPROVED** [review]

**Comment by SentryMan** [comment]
I think we should be good for an RC so I can try this stuff out for real. Unless you have some other ideas for features?

**Comment by rbygrave** [comment]
> good for an RC

Yeah cool.  I'll roll one out when I get home.  

I will look to add a separate helper module to avaje-jex to support htmx features (to match the htmx support we have for nima/helidon).

**Pull request merged**
